# Site settings
title: yaoskyer
description: 'Jekyll-Uno - a minimal, responsive theme for Jekyll'
url: 'http://yaoskyer.github.io'
baseurl: 
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'yaoskyer'
  email: yaoskyer@163.com
  twitter_username: yaoskyer
  facebook_username: yaoskyer
  github_username:  yaoskyer
  linkedin_username:  yaoskyer

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
